fix Publons plugin for OJS3.3.0-6
publons/ojs_3_plugin pull request #12
Opened 2021-05-21 23:50 UTC by huifeidepangzi

2021-05-21 23:51 UTC, huifeidepangzi commented on PublonsPlugin.inc.php
> +    // function getInstallSchemaFile() {
This function has been set as `final` for OJS3.3.0-6  so we can not override it anymore, the PR is here:
https://github.com/pkp/pkp-lib/commit/ebaf20b7ca85559bc48a2d69415ef3e992354e78

2021-05-21 23:55 UTC, huifeidepangzi commented on PublonsPlugin.inc.php
> +    function getInstallMigration() {
Install of using `getInstallSchemaFile`, now we should use `getInstallMigration` to define the db table schema, some examples: 
https://github.com/pkp/sword/blob/f1a4e8535dc7a8ce1976f0bf52834111ce448a42/classes/SwordSchemaMigration.inc.php
https://github.com/ajnyga/funding/blob/7e468f579f54add040024d7ceea8e2f7fd10d483/FundingSchemaMigration.inc.php#L19

The database table that we created:
![image](https://user-images.githubusercontent.com/21093396/119208051-a18b9c80-baf4-11eb-851b-d0fff5a040da.png)

2021-05-21 23:56 UTC, huifeidepangzi commented on classes/PublonsReviewsDAO.inc.php
> -        $result->Close();
This code will cause the crash of the step4 page loading, remove it because seems it is not necessary, example: https://github.com/pkp/pkp-lib/blob/0462408c0a7e0537f1fdcd5c6588fde651fb14ce/classes/context/ContextDAO.inc.php#L62

2021-05-22 00:01 UTC, huifeidepangzi commented on classes/PublonsSchemaMigration.inc.php
> + * Copyright (c) 2000-2021 John Willinsky
From OJS 3.3 the XML locale support is removed, so we need to re-define these .po files https://forum.pkp.sfu.ca/t/ojs-3-3-0-3-hash-tags-appearing-in-child-theme-names/66000/2

.po file example:
https://github.com/pkp/ojs/blob/8b86bbca41c27862618024dde7e248b9b5336354/plugins/importexport/datacite/locale/pl_PL/locale.po

2021-05-22 00:01 UTC, huifeidepangzi commented on locale/ru_RU/locale.xml
> +  </message>
missed message endblock tag

2021-05-22 21:59 UTC, huifeidepangzi commented on PublonsPlugin.inc.php
> -    function getVersion() {
remove useless code, they only are only used to support OJS version before and after 3.1.1.4, but now the OJS version that this plugin support will always be higher than 3.3.0.6

2021-05-22 22:02 UTC, huifeidepangzi commented on classes/PublonsSchemaMigration.inc.php
> +class PublonsSchemaMigration extends Migration {
The database table schema for OJS3.2

publons_reviews_settings:
![publons_reviews_settings_table_schema](https://user-images.githubusercontent.com/21093396/119241890-dc054000-bbad-11eb-9bbc-21837194e434.png)

publons_reviews
![publons_reviews_table_schema](https://user-images.githubusercontent.com/21093396/119241892-dd366d00-bbad-11eb-84ed-15ce3ec82018.png)

2021-05-22 22:04 UTC, huifeidepangzi commented on classes/PublonsSchemaMigration.inc.php
> +class PublonsSchemaMigration extends Migration {
From OJS 3.3 the XML locale support is removed, so we need to re-define these .po files https://forum.pkp.sfu.ca/t/ojs-3-3-0-3-hash-tags-appearing-in-child-theme-names/66000/2

.po file example:
https://github.com/pkp/ojs/blob/8b86bbca41c27862618024dde7e248b9b5336354/plugins/importexport/datacite/locale/pl_PL/locale.po

2021-05-22 22:05 UTC, huifeidepangzi commented on PublonsPlugin.inc.php
> -    function getInstallSchemaFile() {
This function has been set as final for OJS3.3.0-6 so we can not override it anymore, the PR is here:
pkp/pkp-lib@ebaf20b

2021-05-22 22:07 UTC, huifeidepangzi commented on locale/en_US/locale.po
> +msgid "user.email"
From OJS 3.3 the XML locale support is removed, so we need to re-define these .po files https://forum.pkp.sfu.ca/t/ojs-3-3-0-3-hash-tags-appearing-in-child-theme-names/66000/2

.po file example:
https://github.com/pkp/ojs/blob/8b86bbca41c27862618024dde7e248b9b5336354/plugins/importexport/datacite/locale/pl_PL/locale.po

2021-05-24 00:33 UTC, joopeed requested changes
All of these looks great to me, Yi. My only worry would be whether these changes are backwards compatible or not. Can we do a run through some of the release versions and make sure the plugin still works? Seems like we're making things work on the latests OJS version but I'm not convinced this would work for previous versions?

2021-05-24 00:39 UTC, huifeidepangzi commented
> All of these looks great to me, Yi. My only worry would be whether these changes are backwards compatible or not. Can we do a run through some of the release versions and make sure the plugin still works? Seems like we're making things work on the latests OJS version but I'm not convinced this would work for previous versions?

Hi Joao, thanks for the review. Yes it won't compatible with the old OJS env, the main reason for this is that the OJS earlier than 3.2 won't support `getInstallMigration` (don't have this function definition in the base class), whereas the OJS later than 3.3 won't support `getInstallSchemaFile` (they add final keyword for this function so we can not override it anymore).

2021-05-24 01:25 UTC, joopeed commented
So are we happy to drop support for these previous versions?

2021-05-24 01:27 UTC, huifeidepangzi commented
> So are we happy to drop support for these previous versions?

We won't drop the supported of previous version, we still have them, we add a new release to support the new OJS version
![image](https://user-images.githubusercontent.com/21093396/119284400-b8b4c080-bc93-11eb-82bf-62d6d1498402.png)

2021-05-24 01:29 UTC, joopeed commented
But the new version only supports 3.3 or later, right?

2021-05-24 04:10 UTC, huifeidepangzi commented
> But the new version only supports 3.3 or later, right?

yes, the code can not be compatible for earlier OJS version because of the way OJS change their code

2021-05-24 04:25 UTC, joopeed approved these changes
LGTM

2021-05-25 02:31 UTC, merged